require('./gulp/build.dev');
require('./gulp/build.dist');
require('./gulp/clean');
require('./gulp/default');
require('./gulp/preview');
require('./gulp/pug2html');
require('./gulp/scripts');
require('./gulp/styles');
require('./gulp/watch');
